package com.mycompany.myapp;


import com.codename1.ui.Command;
import com.codename1.ui.Dialog;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.SideMenuBar;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.layouts.FlowLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.mycompany.myapp.events.IGameSavedListener;
import com.mycompany.myapp.events.IPlayerChangedListener;
import com.mycompany.myapp.events.PlayerChangedEvent;
import com.mycompany.myapp.gui.MainScreen;
import com.mycompany.myapp.gui.SetUpScreen;
import com.mycompany.myapp.timers.SimpleDefaultTimer;


/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication implements IGameSavedListener, IPlayerChangedListener {


    private Form current, hi;
    private Resources theme;
    private Game game;
    private MainScreen ms;
    
    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }

        game=new Game();
        hi = new Form("Chess Clock", new FlowLayout());
        UIManager.getInstance().getLookAndFeel().setMenuBarClass(SideMenuBar.class);
        Display.getInstance().setCommandBehavior(Display.COMMAND_BEHAVIOR_SIDE_NAVIGATION);
        ms = getNewMainScreen(game, this);
        hi.add(ms);
        hi.addCommand(new Command("New Game"){
            @Override
            public void actionPerformed(ActionEvent evt) {
                if(game!=null){
                    game.stop();
                }               
                game = new Game();
                hi.removeAll();
                SetUpScreen sc = new SetUpScreen(game);
                sc.getListeners().add(MyApplication.this);
                hi.add(sc);
                hi.revalidate();
            }           
        });
        hi.addCommand(new Command("Stop Game"){
            @Override
            public void actionPerformed(ActionEvent evt) {
                if(ms!=null){
                    ms.stopGame();
                }
            }         
        });
        hi.addCommand(new Command("Exit"){
            @Override
            public void actionPerformed(ActionEvent evt) {
                Display.getInstance().exitApplication();
            }
            
        });
        hi.show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
     
    public MainScreen getNewMainScreen(final Game game, final IPlayerChangedListener pl){
        ms = new MainScreen(game, new SimpleDefaultTimer());
        ms.getPlayerChangedListeners().add(pl);
        return ms;
    }
    
    public void destroy() {
    }

    @Override
    public void gameSaved(Game game) {
        hi.removeAll();
        hi.add(getNewMainScreen(game, this));
        hi.revalidate();
    }

    @Override
    public void onPlayerChanged(PlayerChangedEvent evt) {
        game.onPush();
    }
   

}
